COMMENT

   **************************************************
   File generated by: neuroConstruct v1.4.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   Gran_H_98 (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = SI Units 
   /channelml/notes = A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a      Detailed Network Model of the Cerebellar Granule ... 
   /channelml/channel_type/@name = Gran_H_98 
   /channelml/channel_type/status/@value = stable 
   /channelml/channel_type/status/comment = Verified equivalence of NEURON and GENESIS mapping to orig GENESIS impl from www.tnb.ua.ac.be 
   /channelml/channel_type/status/comment = Verified equivalence of NEURON and GENESIS mapping to orig GENESIS impl from www.tnb.ua.ac.be 
   /channelml/channel_type/status/issue = A values don't match table 1 in M and DeS 98 
   /channelml/channel_type/status/contributor/name = Padraig Gleeson 
   /channelml/channel_type/notes = Anomalous inward rectifying H conductance 
   /channelml/channel_type/authorList/modelAuthor[1]/name = Maex, R. 
   /channelml/channel_type/authorList/modelAuthor[2]/name = De Schutter, E. 
   /channelml/channel_type/authorList/modelTranslator/name = Padraig Gleeson 
   /channelml/channel_type/authorList/modelTranslator/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator/email = p.gleeson - at - ucl.ac.uk 
   /channelml/channel_type/publication/fullTitle = Maex, R and De Schutter, E.             Synchronization of Golgi and Granule Cell Firing in a Detailed Network Model of the             cerebellar Gra ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9819260&amp;dopt=Abstract 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = h 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0.30905062 
   /channelml/channel_type/current_voltage_relation/@default_erev = -0.042 
   /channelml/channel_type/current_voltage_relation/q10_settings/@q10_factor = 3 
   /channelml/channel_type/current_voltage_relation/q10_settings/@experimental_temp = 17.350264793 
   /channelml/channel_type/current_voltage_relation/offset/@value = 0.01 
   /channelml/channel_type/current_voltage_relation/gate/@name = n 
   /channelml/channel_type/current_voltage_relation/gate/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate/closed_state/@id = n0 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@id = n 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@name = alpha 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@from = n0 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@to = n 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@expr_form = exponential 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@rate = 0.8 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@scale = -0.01100110011 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@midpoint = -0.075 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@name = beta 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@from = n 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@to = n0 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@expr_form = exponential 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@rate = 0.8 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@scale = 0.01100110011 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@midpoint = -0.075 

// File from which this was generated: /home/padraig/neuroConstruct/testProjects/TestHDF5/cellMechanisms/Gran_H_98/H_Chan.xml

// XSL file with mapping to simulator: /home/padraig/neuroConstruct/testProjects/TestHDF5/cellMechanisms/Gran_H_98/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: SI Units

COMMENT
    A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a 
    Detailed Network Model of the Cerebellar Granule Cell Layer
ENDCOMMENT

TITLE Channel: Gran_H_98

COMMENT
    Anomalous inward rectifying H conductance
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX Gran_H_98
    USEION h READ eh WRITE ih VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE ninf, ntau
    
}

PARAMETER { 
      

    gmax = 0.000030905062 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of h
    eh (mV)
    ? The outward flow of ion: h calculated by rate equations...
    ih (mA/cm2)
    
    
    gion (S/cm2)
    ninf
    ntau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((n)^1)      

    ih = gion*(v - eh)
            

}



INITIAL {
    
    eh = -42
        
    rates(v)
    n = ninf
        
    
}
    
STATE {
    n
    
}

DERIVATIVE states {
    rates(v)
    n' = (ninf - n)/ntau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_n, A_alpha_n, B_alpha_n, Vhalf_alpha_n, A_beta_n, B_beta_n, Vhalf_beta_n
        
    TABLE ninf, ntau
 DEPEND celsius
 FROM -100 TO 100 WITH 400
    
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_n = 3^((celsius - 17.350264793)/10)
    
    ? There is a voltage offset of 0.01. This will shift the dependency of the rate equations 
    v = v - (10)
    
            
                
           

        
    ?      ***  Adding rate equations for gate: n  ***
        
    ? Found a parameterised form of rate equation for alpha, using expression: A*exp((v-Vhalf)/B)
    A_alpha_n = 0.8
    B_alpha_n = -0.01100110011
    Vhalf_alpha_n = -0.075   
    
    ? Unit system in ChannelML file is SI units, therefore need to convert these to NEURON quanities...
    
    A_alpha_n = A_alpha_n * 0.001   ? 1/ms
    B_alpha_n = B_alpha_n * 1000   ? mV
    Vhalf_alpha_n = Vhalf_alpha_n * 1000   ? mV
          
                     
    alpha = A_alpha_n * exp((v - Vhalf_alpha_n) / B_alpha_n)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A*exp((v-Vhalf)/B)
    A_beta_n = 0.8
    B_beta_n = 0.01100110011
    Vhalf_beta_n = -0.075   
    
    ? Unit system in ChannelML file is SI units, therefore need to convert these to NEURON quanities...
    
    A_beta_n = A_beta_n * 0.001   ? 1/ms
    B_beta_n = B_beta_n * 1000   ? mV
    Vhalf_beta_n = Vhalf_beta_n * 1000   ? mV
          
                     
    beta = A_beta_n * exp((v - Vhalf_beta_n) / B_beta_n)
    
    ntau = 1/(temp_adj_n*(alpha + beta))
    ninf = alpha/(alpha + beta)
          
       
    
    ?     *** Finished rate equations for gate: n ***
    

         

}


UNITSON


