#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/matteo/nrnmpi/"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/matteo/nrnmpi//x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/matteo/neuroConstruct/testProjects/TestInputGeneration/generatedNEURON/x86_64/.libs/libnrnmech.so" "$@"
