COMMENT

   **************************************************
   File generated by: neuroConstruct v1.4.1 
   **************************************************


ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: SI Units

COMMENT
    A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a 
    Detailed Network Model of the Cerebellar Granule Cell Layer
ENDCOMMENT

TITLE Channel: Gran_H_98

COMMENT
    Anomalous inward rectifying H conductance
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX Gran_H_98
    USEION h READ eh WRITE ih VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE ninf, ntau
    
}

PARAMETER { 
      

    gmax = 0.000030905062 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of h
    eh (mV)
    ? The outward flow of ion: h calculated by rate equations...
    ih (mA/cm2)
    
    
    gion (S/cm2)
    ninf
    ntau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((n)^1)      

    ih = gion*(v - eh)
            

}



INITIAL {
    
    eh = -42
        
    rates(v)
    n = ninf
        
    
}
    
STATE {
    n
    
}

DERIVATIVE states {
    rates(v)
    n' = (ninf - n)/ntau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_n, A_alpha_n, B_alpha_n, Vhalf_alpha_n, A_beta_n, B_beta_n, Vhalf_beta_n
        
    TABLE ninf, ntau
 DEPEND celsius
 FROM -100 TO 100 WITH 400
    
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_n = 3^((celsius - 17.350264793)/10)
    
    ? There is a voltage offset of 0.01. This will shift the dependency of the rate equations 
    v = v - (10)
    
            
                
           

        
    ?      ***  Adding rate equations for gate: n  ***
        
    ? Found a parameterised form of rate equation for alpha, using expression: A*exp((v-Vhalf)/B)
    A_alpha_n = 0.8
    B_alpha_n = -0.01100110011
    Vhalf_alpha_n = -0.075   
    
    ? Unit system in ChannelML file is SI units, therefore need to convert these to NEURON quanities...
    
    A_alpha_n = A_alpha_n * 0.001   ? 1/ms
    B_alpha_n = B_alpha_n * 1000   ? mV
    Vhalf_alpha_n = Vhalf_alpha_n * 1000   ? mV
          
                     
    alpha = A_alpha_n * exp((v - Vhalf_alpha_n) / B_alpha_n)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A*exp((v-Vhalf)/B)
    A_beta_n = 0.8
    B_beta_n = 0.01100110011
    Vhalf_beta_n = -0.075   
    
    ? Unit system in ChannelML file is SI units, therefore need to convert these to NEURON quanities...
    
    A_beta_n = A_beta_n * 0.001   ? 1/ms
    B_beta_n = B_beta_n * 1000   ? mV
    Vhalf_beta_n = Vhalf_beta_n * 1000   ? mV
          
                     
    beta = A_beta_n * exp((v - Vhalf_beta_n) / B_beta_n)
    
    ntau = 1/(temp_adj_n*(alpha + beta))
    ninf = alpha/(alpha + beta)
          
       
    
    ?     *** Finished rate equations for gate: n ***
    

         

}


UNITSON


