#  ******************************************************
# 
#     File generated by: neuroConstruct v1.5.1
# 
#  ******************************************************

import neuron
from neuron import hoc
import nrn

hoc.execute('load_file("TestHDF5.hoc")')
